# Setup
title: hexso
description: 꾸준히 조금씩 즐기자
url: https://hexso.github.io
avatar: /avatar.jpeg
paginate: 8
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: hexso
  card: summary
logo: logo.png
social:
  name: Junho Kim
  links:
    -https://twitter.com/
    - https://github.com/hexso
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Junho Kim
  url: https://github.com/hexso/
  email: kesu82091@gmail.com
